User history
Coding-in-community/fingest pull request #8
Opened 2021-05-17 21:04 UTC by Gabriel-Ayala

Pull Request feito para implementar a História de Usuários no Backend

2021-05-17 21:17 UTC, thiagolima86 requested changes
É bom usar o rubocop e o reek, pra formatar o código e seria interessante remover arquivos que não fazem nada e os comentarios. O arquivo no model esta vazio, mas não deve remover ele, porque só a presença dele faz coisas acontecerem.

2021-05-17 21:17 UTC, thiagolima86 commented on app/assets/stylesheets/scaffolds.scss
> +body {
Esse aquivo é um css criado automaticamente pelo scaffold. Ele pode atrapalhar outros css que a gente escrever. melhor não subir ele.

2021-05-17 21:17 UTC, thiagolima86 commented on app/assets/stylesheets/user.scss
> +// Place all the styles related to the user controller here.
Esses arquivos que não tem nada escrito, melhor não comitar eles.

2021-05-18 12:55 UTC, Gabriel-Ayala commented on app/assets/stylesheets/scaffolds.scss
> +body {
apagado

2021-05-18 12:55 UTC, Gabriel-Ayala commented on app/assets/stylesheets/user.scss
> +// Place all the styles related to the user controller here.
apagado

2021-05-20 00:00 UTC, thiagolima86 commented
Vamos melhorar o titulo deixar ele mais claro, não precisa dizer que é uma historia. só dizewr o que ele faz. 
* É bom começar com verbos declarativos como: _adiciona, corrige, implementa, cria, atualiza, resolve._
* Evitar usar palavras como palavras no titulo como: Commit, pull request, task, historia etc...
* O texto precisa exprimir o que a PR resolve e não apontar para uma historia.

Exemplo:
### Implementar os usuários

2021-05-20 00:36 UTC, thiagolima86 commented
Vamos ver a possibilidade e reverter esse commit do rubocop. Talvez a gente possa desativar algumas pastas deles e deixar ele assistindo somente, as pastas /app, /config e /spec. O resto não precisa.

tambem vamos estudar melhor esse ` \# frozen_string_literal: true`, Isso é novo no ruby, ainda não sei se é correto. vamos perguntar no grupo.

2021-05-20 22:24 UTC, krlosgilson reviewed
Bom, a história ficou extensa e com propósitos distintos a serem analisados. Assim, alguns commits poderiam ser aprovados e outros não. No caso do Rubocop, um dos motivos foi a alteração de muitos arquivos por causa do tipo de aspa utilizada.

2021-05-20 23:24 UTC, renanorodrigues commented on app/controllers/users_controller.rb
> +    params.fetch(:user, {})
Aqui ficaria os atributos permitidos pelo controller. É uma medida de segura.

2021-05-20 23:28 UTC, renanorodrigues commented on app/views/users/show.html.erb
> +
Aqui podia só mostrar o objeto usuário para ver as informações.

2021-05-20 23:39 UTC, renanorodrigues requested changes
Muito do que tu fez foi por conta das correções do rubocop. Tenta usar o comando nos arquivos em que você trabalhou. Mas fora isso, só as ressalvas apontadas.

2021-05-21 18:51 UTC, closed without merging